### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gsquire** [rggr/capella#2]
Below is a rough checklist of things that need to get done:
- [x] More unit tests for the parser.
- [x] Attend to the TODO comments.
- [x] Investigate how to do caching/batching of metrics.
- [x] Look into how to publish to a backend like graphite or just dumping it to the console.
- [x] Start writing a configuration module for setting up the server.
- [ ] See if any other protocols are desired. (e.g. TCP)
- [ ] Try and reach parity with other StatsD implementations in other language and the original.
- [x] Consider adding in server-side logging to see errors and internal metrics.
